network:
  version: 2
  renderer: networkd
  ethernets:
    enp2s0:
      match:
        macaddress: {SYSTEM_MACADDRESS}    
      dhcp4: true
      wakeonlan: true
      addresses:
        - {SYSTEM_IP}/24
      gateway4: 192.168.0.1
      nameservers:
          addresses: [8.8.8.8, 1.1.1.1]
